# Generated by Django 4.2.1 on 2023-05-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
