# Generated by Django 4.2.1 on 2023-05-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0003_alter_registration_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='corporation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='municipality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='panchayath',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
