# Generated by Django 4.2.1 on 2023-05-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0004_registration_corporation_registration_municipality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='corporation',
            new_name='ward_number',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='district',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='panchayath',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='place',
        ),
    ]
